#!/bin/bash

rails g migration add_attributes_to_users first_name:text last_name:text student_id_number:integer phone_number:text
rails g model Course course_code:text course_name:text
rails g model Instructor first_name:text last_name:text
rails g model Term term_formatted:text
rails g scaffold Lecture user:references course:references instructor:references term:references lecture_name:text chapter:text description:text
rails g model LectureFile lecture:references user:references
rails g scaffold Review user:references lecture:references content:text rating:integer
